from centos:centos7.9.2009
maintainer afcfzf <9301462@qq.com>
label version="1.0"
label description="docker for java server"
expose 8080

run mkdir -p /work/proj/demo
workdir /work/proj/demo

copy ./target/demo-1.0.jar ./
