from redis:7.2.4-alpine
maintainer afcfzf <9301462@qq.com>
label version="1.0"
label description="docker for redis"

RUN mkdir -p /data/software/

RUN ["chmod", "777", "/data/software/"]

WORKDIR /data/software/

