name: deploy-redis
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker_redis
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: swr.cn-north-4.myhuaweicloud.com
          username: ${{ secrets.SWR_DOCKERHUB_USERNAME }}
          password: ${{ secrets.SWR_DOCKERHUB_PASSWORD }}

      - name: Set Bash Env
        run: |
          echo "GIT_HASH_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DOCKER_CONTAINER_NAME=server-demo-redis" >> $GITHUB_ENV
          # show output
          echo "output is ${{ env.GIT_HASH_SHORT }}"

      - name: Build the Docker image
        run: docker build -t ${{ secrets.SWR_DOCKER_REDIS_PATH }}:"$GIT_HASH_SHORT" .

      - name: Docker image push
        run: docker push ${{ secrets.SWR_DOCKER_REDIS_PATH }}:"$GIT_HASH_SHORT"

      #Job starts here
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SWR_SSH_HOST }}
          username: ${{ secrets.SWR_SSH_USER_NAME }}
          password: ${{ secrets.SWR_SSH_PASSWORD }}

          #Bash commands may be placed line by line here
          script: |
            docker login -u ${{ secrets.SWR_DOCKERHUB_USERNAME }} -p ${{ secrets.SWR_DOCKERHUB_PASSWORD }} swr.cn-north-4.myhuaweicloud.com
            docker pull ${{ secrets.SWR_DOCKER_REDIS_PATH }}:${{ env.GIT_HASH_SHORT }}
            docker ps -q --filter "name=${{ env.DOCKER_CONTAINER_NAME }}" | xargs -r docker stop
            docker ps -aq --filter "name=${{ env.DOCKER_CONTAINER_NAME }}" | xargs -r docker rm -f
            docker run -p 6379:6379 -p 8806:3306 --name=${{ env.DOCKER_CONTAINER_NAME }} --restart=always  \
            -v /root/work/proj/java-learn/docker-config/redis:/data/config/redis \
            -v /root/work/proj/java-learn/docker-config/mysql/db:/data/config/mysql/db \
            -v /root/work/proj/java-learn/docker-config/mysql/log:/data/config/mysql/log \
            -v /root/work/proj/java-learn/docker-config/mysql/cgroup:/sys/fs/cgroup \
            -v /root/work/proj/java-learn/docker-config/mysql/my.cnf:/etc/my.cnf \
            -d ${{ secrets.SWR_DOCKER_REDIS_PATH }}:${{ env.GIT_HASH_SHORT }}
