name: deploy-redis
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker_redis
    steps:
      - uses: actions/checkout@v4
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: swr.cn-north-4.myhuaweicloud.com
          username: ${{ secrets.SWR_DOCKERHUB_USERNAME }}
          password: ${{ secrets.SWR_DOCKERHUB_PASSWORD }}

      - name: Set Bash Env
        run: echo "GIT_HASH_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build -t ${{ secrets.SWR_DOCKER_REDIS_PATH }}:"$GIT_HASH_SHORT" .

      - name: Docker image push
        run: docker push ${{ secrets.SWR_DOCKER_REDIS_PATH }}:"$GIT_HASH_SHORT"

      #Job starts here
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SWR_SSH_HOST }}
          username: ${{ secrets.SWR_SSH_USER_NAME }}
          password: ${{ secrets.SWR_SSH_PASSWORD }}

          #Bash commands may be placed line by line here
          script: |
            docker login -u ${{ secrets.SWR_DOCKERHUB_USERNAME }} -p ${{ secrets.SWR_DOCKERHUB_PASSWORD }} swr.cn-north-4.myhuaweicloud.com
            echo 结果:   ${{ secrets.SWR_DOCKER_REDIS_PATH }}:${{ env.GIT_HASH_SHORT }}
            docker pull ${{ secrets.SWR_DOCKER_REDIS_PATH }}:${{ env.GIT_HASH_SHORT }}
            docker ps -q --filter "name=server-demo-container" | xargs -r docker stop
            docker ps -aq --filter "name=server-demo-container" | xargs -r docker rm -f
            docker run -d -p 8080:8080 --name=server-demo-container --restart=always ${{ secrets.SWR_DOCKER_REDIS_PATH }}:${{ env.GIT_HASH_SHORT }}