name: deploy-server
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/mini_service
    # strategy:
    #   matrix:
    #     node-version: [16.13.x]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - run: touch ./src/main/resources/secrets.properties
      - run: echo "jasypt.encryptor.password=${{ secrets.JASYPT_SECRET }}" > ./src/main/resources/secrets.properties
      - run: ls ./src/main/resources/

      # - name: Build with Maven
      #   run: mvn --batch-mode --update-snapshots verify
      - name: Build with gradle
        run: ../gradlew clean build

      # --- node below ---
      # - uses: actions/checkout@v3
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # - name: Install Dependencies
      #   run: npm i -g yarn && yarn

      # - name: Build
      #   run: yarn build

      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: swr.cn-north-4.myhuaweicloud.com
          username: ${{ secrets.SWR_DOCKERHUB_USERNAME }}
          password: ${{ secrets.SWR_DOCKERHUB_PASSWORD }}

      - name: Set Bash Env
        run: |
          echo "GIT_HASH_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DOCKER_CONTAINER_NAME=server-app-mini" >> $GITHUB_ENV
          echo "DOCKER_APP_MINI_NAME=swr.cn-north-4.myhuaweicloud.com/mark-app/server-app-mini"  >> $GITHUB_ENV
          # show output
          echo "output is ${{ env.GIT_HASH_SHORT }}"

      # - name: Set Bash Env
      #   run: echo "GIT_HASH_SHORT=533a05d" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build -t ${{ env.DOCKER_APP_MINI_NAME }}:"$GIT_HASH_SHORT" .

      - name: Docker image push
        run: docker push ${{ env.DOCKER_APP_MINI_NAME }}:"$GIT_HASH_SHORT"

      #Job starts here
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SWR_SSH_HOST }}
          username: ${{ secrets.SWR_SSH_USER_NAME }}
          password: ${{ secrets.SWR_SSH_PASSWORD }}

          #Bash commands may be placed line by line here
          script: |
            docker login -u ${{ secrets.SWR_DOCKERHUB_USERNAME }} -p ${{ secrets.SWR_DOCKERHUB_PASSWORD }} swr.cn-north-4.myhuaweicloud.com
            docker pull ${{ env.DOCKER_APP_MINI_NAME }}:${{ env.GIT_HASH_SHORT }}
            docker ps -q --filter "name=server-app-container" | xargs -r docker stop
            docker ps -aq --filter "name=server-app-container" | xargs -r docker rm -f
            docker run -p 8080:8080 --name=server-app-container --restart=always \
            -v /root/work/proj/service-app/docker-config/buckets:/data/buckets \
            -d ${{ env.DOCKER_APP_MINI_NAME }}:${{ env.GIT_HASH_SHORT }}


